---
apiVersion: batch/v2alpha1
kind: CronJob
metadata:
  name: k8s-cleanup
  namespace: kube-system
spec:
  schedule: "0 */3 * * *"
  concurrencyPolicy: "Forbid"
  jobTemplate:
    spec:
      template:
        metadata:
          name: k8s-cleanup
        spec:
          restartPolicy: OnFailure
          serviceAccountName: k8s-cleanup
          containers:
            - name: k8s-cleanup
              image: gcr.io/synalabs-marketplace/k8s-cleanup@sha256:4f9d2bab4bbaeb4f04cac1492b36cdab35fbb0f126ef145cfc68c1fe69b152cb
              command: ["/bin/bash", "/bin/k8s-clean.sh"]
              imagePullPolicy: Always
              resources:
                requests:
                  cpu: 100m
                  memory: 50Mi
