apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: {{ .Chart.Name }}
rules: 
  - apiGroups: ["*"]
    resources: ["replicasets", "jobs", "pods"]
    verbs: ["get", "list", "delete", "update"]
